### ISSUE TITLE
Excel file

### ISSUE THREAD

**Issue by DPontes** [paulbarna/CarND-Capstone#1]
Shouldn't the excel file be available online, i.e.: in Google Docs or something similar?
I believe this solution would be easier and less prone to errors than having an excel file in the repo..

**Comment by paulbarna** [comment]
Good idea. Can you upload it in Google Drive and share it with the rest of us?

**Comment by DPontes** [comment]
Yes. I'll close this issue when it's done

**Comment by DPontes** [comment]
File added to GDrive: https://docs.google.com/spreadsheets/d/1fkSX7_w8WGs1uY0hH_y73P-zfWBtfHoASNJWzl7l8n0/edit?usp=sharing
